In [1]:
import torch

## Entendendo mecanismo de marcaramento

In [3]:
a = torch.randn(3, 3)
print(a)
a = torch.tril(a, diagonal=0) # valor 0 é o valor padrão do argumento 'diagonal'
print(a)

tensor([[-0.6181, -0.3455,  0.6579],
        [-0.4218,  0.3721,  0.6876],
        [ 0.3069, -1.2369, -0.2674]])
tensor([[-0.6181,  0.0000,  0.0000],
        [-0.4218,  0.3721,  0.0000],
        [ 0.3069, -1.2369, -0.2674]])


Note que para o dado caso acima. a função "torch.tril" acaba por mantem apenas os elementos que estão abaixo da diagonal principal (incluindo a propria diagonal). Isso pode ser relacionado com a nomenclatura da função.

"tril" = "triangulo" + "lower" = só mantém os abaixo (lower)

da mesma forma tem o "triu" que a ideia é a mesma, mas ao contrário.

"triu" = "triangulo" + "upper" = só mantém os de cima (upper)


Tudo inclui a diagonal principal e isso é devido ao argumento "diagonal=0" que vem por padrão. Caso você adicione valores vc vai deslocando a diagonal:

In [11]:
a = torch.randn(5, 5)
print("\n")
print(a)
a = torch.tril(a, diagonal=0) # valor 0 é o valor padrão do argumento 'diagonal'
print("\n")
print(a)
a = torch.tril(a, diagonal=-1) # valor 0 é o valor padrão do argumento 'diagonal'
print("\n")
print(a)
a = torch.tril(a, diagonal=-2) # valor 0 é o valor padrão do argumento 'diagonal'
print("\n")
print(a)
a = torch.tril(a, diagonal=-3) # valor 0 é o valor padrão do argumento 'diagonal'
print("\n")
print(a)



tensor([[-0.7034, -0.0214, -0.3853, -0.5045,  0.3257],
        [-1.2644, -1.0050,  0.9983, -3.3491,  0.1454],
        [ 1.3271, -1.2806,  2.4135, -0.5170, -0.3577],
        [ 0.8507,  0.5951, -1.0930, -1.0507, -0.0613],
        [-1.4354, -0.5562, -0.8539,  0.3615,  0.4219]])


tensor([[-0.7034,  0.0000,  0.0000,  0.0000,  0.0000],
        [-1.2644, -1.0050,  0.0000,  0.0000,  0.0000],
        [ 1.3271, -1.2806,  2.4135,  0.0000,  0.0000],
        [ 0.8507,  0.5951, -1.0930, -1.0507,  0.0000],
        [-1.4354, -0.5562, -0.8539,  0.3615,  0.4219]])


tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-1.2644,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.3271, -1.2806,  0.0000,  0.0000,  0.0000],
        [ 0.8507,  0.5951, -1.0930,  0.0000,  0.0000],
        [-1.4354, -0.5562, -0.8539,  0.3615,  0.0000]])


tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.3271,  0.0000,  0.0000,  0.0000,  0.0000],

se forem positivos vai subindo a diagonal

In [20]:
a = torch.randn(5, 5)
print("\n")
print(a)
a = torch.tril(a, diagonal=2) # valor 0 é o valor padrão do argumento 'diagonal'
print("\n")
print(a)





tensor([[-0.0645,  1.3047,  0.4277,  0.5252,  0.7521],
        [ 0.7505, -0.2314,  0.7378, -1.1488,  1.7457],
        [ 1.3112, -1.1668, -0.7403,  0.0454, -0.7284],
        [-0.0897,  0.4965,  1.4634,  0.6890,  0.8628],
        [ 0.3059, -0.6464, -0.8228,  0.8267,  0.7062]])


tensor([[-0.0645,  1.3047,  0.4277,  0.0000,  0.0000],
        [ 0.7505, -0.2314,  0.7378, -1.1488,  0.0000],
        [ 1.3112, -1.1668, -0.7403,  0.0454, -0.7284],
        [-0.0897,  0.4965,  1.4634,  0.6890,  0.8628],
        [ 0.3059, -0.6464, -0.8228,  0.8267,  0.7062]])


mesma coisa para o upper:

In [24]:
a = torch.randn(5, 5)
print("\n")
print(a)
a = torch.triu(a, diagonal=0) # valor 0 é o valor padrão do argumento 'diagonal'
print("\n")
print(a)
a = torch.triu(a, diagonal=1) # valor 0 é o valor padrão do argumento 'diagonal'
print("\n")
print(a)



tensor([[ 1.7025, -1.1540, -0.8455,  1.0116,  0.9915],
        [-0.1845,  0.1060,  0.5343, -0.3995,  1.5607],
        [ 0.2892, -0.4093, -0.4925,  0.0377,  1.0571],
        [-1.2447, -0.7098, -0.3556,  1.9101,  1.2946],
        [-0.5953,  1.6353,  0.1490, -0.1305,  0.4553]])


tensor([[ 1.7025, -1.1540, -0.8455,  1.0116,  0.9915],
        [ 0.0000,  0.1060,  0.5343, -0.3995,  1.5607],
        [ 0.0000,  0.0000, -0.4925,  0.0377,  1.0571],
        [ 0.0000,  0.0000,  0.0000,  1.9101,  1.2946],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.4553]])


tensor([[ 0.0000, -1.1540, -0.8455,  1.0116,  0.9915],
        [ 0.0000,  0.0000,  0.5343, -0.3995,  1.5607],
        [ 0.0000,  0.0000,  0.0000,  0.0377,  1.0571],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  1.2946],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])


In [26]:
a = torch.randn(5, 5)
print("\n")
print(a)

a = torch.triu(a, diagonal=-1) # valor 0 é o valor padrão do argumento 'diagonal'
print("\n")
print(a)



tensor([[-0.2580,  0.2264,  0.1828, -0.7562,  0.7760],
        [-1.5117,  0.8059, -0.8755,  1.8465, -0.3779],
        [ 0.3291,  0.9031,  0.6587,  0.4519, -0.1130],
        [-0.3485, -0.3084, -0.9972,  0.4186,  0.2218],
        [ 2.0438,  0.6494, -0.1084,  0.0588,  0.7773]])


tensor([[-0.2580,  0.2264,  0.1828, -0.7562,  0.7760],
        [-1.5117,  0.8059, -0.8755,  1.8465, -0.3779],
        [ 0.0000,  0.9031,  0.6587,  0.4519, -0.1130],
        [ 0.0000,  0.0000, -0.9972,  0.4186,  0.2218],
        [ 0.0000,  0.0000,  0.0000,  0.0588,  0.7773]])
